app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

products:
    type:     rest
    resource: AppBundle\Controller\ProductController

categories:
    type:     rest
    resource: AppBundle\Controller\CategoryController

types:
    type:     rest
    resource: AppBundle\Controller\TypeController
